# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            João Eduardo Montandon
description:      'Assistant Professor at COLTEC/UFMG.'
url:              http://jemaf.github.io
baseurl:          /

author:
  name:           'João Eduardo Montandon'
  url:            http://jemaf.github.io

social:
  github:         jemaf
  twitter:        EduMontandon
  lattes:         http://lattes.cnpq.br/4459015753704495
  linkedin:       http://www.linkedin.com/profile/view?id=81602055

analytics:
  google:
    id:           UA-26507443-1
