name: João Eduardo
author: João Eduardo Montandon
baseurl: /jemaf
description: Assistant Professor @ COLTEC
profile_picture: profile.png
github: http://www.github.com/jemaf
twitter: http://www.twitter.com/EduMontandon
facebook: http://www.facebook.com
linkedin: https://www.linkedin.com/profile/view?id=81602055
email: joao.montandon[at]dcc[dot]ufmg[dot]br
location: Belo Horizonte/Brazil
disqus:

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      base_css: "hc"
